on: [push]
name: lolcounter container workflow

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@master

        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}

        -name: Build Image
        - uses: azure/docker-login@v1
          with:
            login-server: cse598bic.azurecr.io
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
        - run: |
            docker build -t cse598bic.azurecr.io/lolcounter:${{ github.sha }} -f lol_gen_alg_frontend/Dockerfile lol_gen_alg_frontend/
            docker push cse598bic.azurecr.io/lolcounter:${{ github.sha }}

        - name: 'Deploy to Azure Container Instances'
          uses: 'azure/aci-deploy@v1'
          with:
            resource-group: cse598
            dns-name-label: https://lolcounter1.azurewebsites.net
            image: cse598bic.azurecr.io/lolcounter:${{ github.sha }}
            registry-username: ${{ secrets.REGISTRY_USERNAME }}
            registry-password: ${{ secrets.REGISTRY_PASSWORD }}
            name: lolcounter1
            location: 'Central US'
